### ISSUE TITLE
Unknown text in settings

### ISSUE THREAD

**Issue by sigmanor** [Cypher-Notepad/Cypher-Notepad#2]
![](https://i.imgur.com/rJHkB6X.gif)

**Comment by LeeDongGeon1996** [comment]
Oh...I think the font doesn't support Korean character. Thank you for letting me know and your attention. I saw your Crypto-Notepad when I decided to develop this program. really well made :)

**Comment by sigmanor** [comment]
> Oh...I think the font doesn't support Korean character. Thank you for letting me know and your attention. I saw your Crypto-Notepad when I decided to develop this program. really well made :)

Yes, It's funny that app name is the same as mine, that why I downloaded and test it :smile:

**Comment by sigmanor** [comment]
@LeeDongGeon1996  I expect that you will add some documentation, because for now I dont really understand how it works, why files encrypted without entering the password etc.

**Comment by LeeDongGeon1996** [comment]
> > Oh...I think the font doesn't support Korean character. Thank you for letting me know and your attention. I saw your Crypto-Notepad when I decided to develop this program. really well made :)
> 
> Yes, It's funny that app name is the same as mine, that why I downloaded and test it 😄

haha I know. It was a coincidence. but I couldn't think of a better name for this. naming is tough thing to me. lolol And about the document.... you're right. I think I need to do it. I had asked my friend to test my app but they also said the same as you. Thank you for your advice.

+++I want the user not to care about encryption things. So I designed the program to generate keys automatically. but I'm not sure it is good or not

**Comment by sigmanor** [comment]
>I want the user not to care about encryption things. So I designed the program to generate keys automatically. but I'm not sure it is good or notI

If generate keys automatically means that any user that open your app in my PC can get access to encrypted files, then its bad idea. Also I cant understand how to open encrypted files in another PC, if key was generated automatically.

Also, I think this is very bad idea:
![](https://i.imgur.com/XPHjrCT.png)

You give information to possible hackers about in what application this file was encrypted. The encrypted file must be depersonalized.

I just share my experience, you decide what to add to the application and what not 😅

**Comment by LeeDongGeon1996** [comment]
Thank you for your advice. I was on vacation. That's why I am sending late reply. I'm sorry for that. 
I have thought about what you said and how to fix it since last night when I came back home. But...I think If I try to fix, it will be long journey. because I have to change lots of thing to fix it. 
Maybe I can fix some minor thing..such as what you told me using screenshot of my program. I had poor knowledge about encryption. and it cause every problems now.
Anyway I will try to fix something and hope somebody use the program. Thanks again for sharing your experience. :)
