### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by maravento** [Cypher-Notepad/Cypher-Notepad#3]
You could publish support for systems compatible with .deb (debian, ubuntu 20.04, etc) or appimage, etc. Thanks in advance

**Comment by LeeDongGeon1996** [comment]
Hi, thank you for your comment!! Actually I'm wondering which is the best way to distribute on Linux system. Could you tell me more about this? I'm not sure I fully understand your words. I know about `.deb` package but have never heard about `.appimage`. Searching about this, I figure out it is very convenient way. But is it frequently used way for distributing these days?

 And also as you know, Java is system independent but I'm worrying my code might be system dependent(i.e File I/O). so I think it needs to be tested on Linux.

**Comment by maravento** [comment]
The standard for linux is to use **deb** (debian, ubuntu, etc) and **rpm** (red hat and derivatives) packages. In this case the dependencies (java, etc) are installed separately.
For Ubuntu and derivates (most popular) you can also create a PPA on [launchpad](https://launchpad.net/). Example:
`sudo apt-add-repository -y ppa:cyphernotepad/ppa`
`sudo apt -y install cyphernotepad`
appimage (or similars) is for packaging program + dependencies into one (similar to a portable program in Windows)
PD: there are many other ways ...

**Comment by LeeDongGeon1996** [comment]
Thank you for your advice. I had considered both using `ppa` and `deb`. I finally decided to make deb package to distribute. I usually prefer traditional ways. 
By bundling JRE using `javapackager`, dependency problem is likely to be solved.
BUT...I got some errors while doing it :( 
So I still keep trying it. 😂

Plus. I've checked `.jar`  of the CN works well on Linux.

**Comment by maravento** [comment]
Publish a .deb version of tests (alpha) with the source code. I am sure that many will help you to fix any bug
