### ISSUE TITLE
License

### ISSUE THREAD

**Issue by parubok** [Cypher-Notepad/Cypher-Notepad#5]
Hi!

Please add a license to the project, so other people will know what they can/cannot do with the code.
It seems that without a license, allowed usages of the code are very limited:
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Thanks!
Eli

**Comment by LeeDongGeon1996** [comment]
Hi,
Thanks for your interests. I'll review some licenses and then add one of them to my project. :)

**Comment by LeeDongGeon1996** [comment]
Added GPL v3.0. Now, you can freely use the source code of Cypher Notepad.
